security/s2a/internal/crypter/aeadcrypter.go
Updated the S2A AEAD crypter interface to include `nonce` and `aad`. These are fields which are not present in ALTS, but required in S2A.
=> Update AEAD crypter interface

security/s2a/internal/crypter/aesgcm.go, security/s2a/internal/crypter/aesgcm_test.go, security/s2a/internal/crypter/common.go, security/s2a/internal/crypter/testdata/aes_gcm_wycheproof.json, security/s2a/internal/crypter/testutil/common.go, security/s2a/internal/crypter/testutil/wycheproofutil.go
Added the initial implementation of S2A AES-GCM as well as the Wycheproof tests. Much of the implementation and some of the tests mirror the AES-GCM implementation in ALTS.
=> Add S2A AES-GCM implementation and Wycheproof Tests

security/s2a/internal/crypter/aeadcrypter.go, security/s2a/internal/crypter/aesgcm.go, security/s2a/internal/crypter/aesgcm_test.go, security/s2a/internal/crypter/common.go, security/s2a/internal/crypter/testutil/common.go
Unexported the AEAD crypter interface, since it will not be used outside of the `crypter` package.
=> Unexport AEAD crypter interface

security/s2a/internal/crypter/aesgcm_test.go, security/s2a/internal/crypter/testutil/common.go, security/s2a/internal/crypter/testutil/wycheproofutil.go
Fixed the error message formatting and changed the `Comment` field in the test vector to `Desc`, as mentioned in #11.
=> Fix formatting issues

security/s2a/internal/crypter/counter.go, security/s2a/internal/crypter/counter_test.go
Added a Counter class for the S2A Half Connection. This will be used in the half connection to keep track of the sequence number which is used as part of the nonce. 
I took the approach of using a byte slice rather than using an integer and converting it to a byte array on the fly whenever `val()` is called. This (using a byte slice) is what is done in ALTS - I'm not sure what the performance differences are but I suspect that this is slightly more efficient than converting an integer on the fly.
Also, I chose to return an error on calling `val` rather than on calling `inc` in case of an overflow, but happy to change that if anyone has other thoughts.
=> Add S2A Half Connection Counter class

security/s2a/internal/crypter/ciphersuite.go, security/s2a/internal/crypter/ciphersuite_test.go, security/s2a/internal/crypter/common.go
Added the ciphersuite interface and implementations to be used in the S2A Half Connection.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/matthewstevenson88/grpc-go/23)
=> Add ciphersuite interface

security/s2a/internal/crypter/counter.go, security/s2a/internal/crypter/counter_test.go
Added the option to specify an initial value when constructing a `counter`. This may be required for the resumption work that will be implemented in S2A.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/matthewstevenson88/grpc-go/30)
=> Add initial value to counter constructor

security/s2a/internal/crypter/common_test.go
Added basic tests for `encrypt` and `decrypt` in `common.go`, using a mock AEAD crypter which just returns the inputted byte slice.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/matthewstevenson88/grpc-go/26)
=> Add common.go unit tests

security/s2a/internal/crypter/common.go, security/s2a/internal/crypter/halfconn.go, security/s2a/internal/crypter/halfconn_test.go
Added the initial S2A Half Connection. This is largely unimplemented, but exposes the basic methods that S2A Half Connection would provide. This also implements `expandLabel` specified in https://tools.ietf.org/html/rfc8446#section-7.1. It basically constructs a HkdfLabel struct (Which is a struct specific to TLS 1.3) and passes that to the underlying HKDF expand function.
One thing that became apparent when implementing `expandLabel` was that calling `h().Size()` is expensive. For example, `h` that is passed in will most likely be something like `sha256.New`. When we call `h()`, we are calling `sha256.New()` and creating a new Hash just to get the length. I think this is quite expensive when all we want is the length of the hash. We are doing this in both `expandLabel` as well as the …
=> Add S2A Half Connection

security/s2a/internal/crypter/aeadcrypter.go, security/s2a/internal/crypter/aesgcm.go, security/s2a/internal/crypter/aesgcm_test.go, security/s2a/internal/crypter/chachapoly.go, security/s2a/internal/crypter/chachapoly_test.go
Removed the `UpdateKey` API from the AEAD crypter interface. This is because we can't allow the AEAD crypter to be mutated while we encrypt/decrypt in the S2A Half Connection. Rather than calling `UpdateKey`, we can just create a new AEAD crypter and reassign it which circumvents the issue of mutating the AEAD crypter while encrypting and decrypting.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/matthewstevenson88/grpc-go/32)
=> Remove UpdateKey API from AEAD crypter

security/s2a/internal/crypter/aeadcrypter.go, security/s2a/internal/crypter/aesgcm.go, security/s2a/internal/crypter/aesgcm_test.go, security/s2a/internal/crypter/chachapoly.go, security/s2a/internal/crypter/chachapoly_test.go, security/s2a/internal/crypter/ciphersuite.go, security/s2a/internal/crypter/ciphersuite_test.go, security/s2a/internal/crypter/halfconn.go, security/s2a/internal/crypter/halfconn_test.go, security/s2a/internal/crypter/testutil/common.go
Looking at https://github.com/golang/go/wiki/CodeReviewComments#initialisms, I think the interface should be called `s2aAEADCrypter` rather than `s2aAeadCrypter` since AEAD is an acronym for *authenticated encryption with associated data*.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/matthewstevenson88/grpc-go/40)
=> Rename s2aAeadCrypter to s2aAEADCrypter

security/s2a/internal/crypter/halfconn.go, security/s2a/internal/crypter/halfconn_test.go
Added the sequence number to `NewHalfConn` to allow the record protocol to pass the initial sequence number to the half connection.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/matthewstevenson88/grpc-go/38)
=> Add sequence number to NewHalfConn

security/s2a/internal/crypter/expander.go, security/s2a/internal/crypter/expander_test.go, security/s2a/internal/crypter/halfconn.go
Removed the hash function from the HKDF expander API and added it to the constructor instead. This should make the API a bit cleaner.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/matthewstevenson88/grpc-go/35)
=> Remove hash function from HKDF expand API

security/s2a/internal/crypter/halfconn.go, security/s2a/internal/crypter/record.go, security/s2a/internal/crypter/record_test.go
Added the S2A record protocol structure. `Read` and `Write` have been left unimplemented for now and will be completed in following PRs.
I've left some TODOs regarding the HalfConn constructor and API. There needs to be some updates to the `HalfConn` API as well as the counter API.
In particular:
- the `HalfConn` constructor needs to take a sequence number
- the counter constructor needs to take an initial value
- I think `HalfConn` needs a `TagSize` API. We can't retrieve the tag size from the AEAD crypter API since the `aeadCrypter` field is private in `HalfConn`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/matthewstevenson88/grpc-go/29)
=> Add S2A record protocol structure

security/s2a/internal/crypter/halfconn.go, security/s2a/internal/crypter/halfconn_test.go, security/s2a/internal/crypter/record.go
Added the `TagSize` API to the half connection. This will allow the record protocol file to access the AEAD crypter's tag size from the half connection. This is needed once we move the AEAD crypter to its own package and the half connection to its own package.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/matthewstevenson88/grpc-go/39)
=> Add TagSize API to the Half Connection

security/s2a/internal/record/record.go
Fix NewHalfConn to New renaming. I accidentally unchecked the `record.go` file before merging #41, so the master `record.go` file isn't working right now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/matthewstevenson88/grpc-go/43)
=> Fix NewHalfConn to New renaming

security/s2a/internal/handshaker/handshaker.go, security/s2a/internal/record/record.go, security/s2a/internal/record/record_test.go
Fixed the Handshaker service capitalization formatting. I believe the "S" should be capitalized (https://github.com/golang/go/wiki/CodeReviewComments#initialisms). The spacing was automatically changed by my linter.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/matthewstevenson88/grpc-go/46)
=> Fix Handshaker Service Address naming

security/s2a/internal/handshaker/handshaker.go, security/s2a/internal/handshaker/handshaker_test.go
I was going through the handshaker service code to understand it while working on the public APIs. I found some nits and inconsistencies with the rest of the code base and some of the Go styling guidelines. I've also propagated the error returned by `Close` and removed the `context` field from the methods which did not require it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/matthewstevenson88/grpc-go/47)
=> Clean up handshaker service styling

security/s2a/internal/handshaker/service/service.go, security/s2a/internal/handshaker/service/service_test.go
Previously, `hsConn` was a single value. If an application specifies 2 different handshaker service addresses, this would result in strange behavior where the first handshaker address that gets called into `Dial` would always be used. By using a map, we allow a handshaker connection per handshaker service address.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/matthewstevenson88/grpc-go/50)
=> Change hsConn to a map

security/s2a/internal/authinfo/authinfo.go, security/s2a/internal/authinfo/authinfo_test.go, security/s2a/internal/fakehandshaker/main.go, security/s2a/internal/fakehandshaker/s2a_service.go, security/s2a/internal/fakehandshaker/s2a_service_test.go, security/s2a/internal/record/internal/aeadcrypter/aeadcrypter.go, security/s2a/internal/record/internal/aeadcrypter/common.go, security/s2a/internal/record/internal/aeadcrypter/common_test.go, security/s2a/internal/record/internal/aeadcrypter/testutil/common.go, security/s2a/internal/record/internal/aeadcrypter/testutil/wycheproofutil.go, security/s2a/internal/record/internal/halfconn/ciphersuite.go, security/s2a/internal/record/internal/halfconn/ciphersuite_test.go, security/s2a/internal/record/internal/halfconn/counter.go, security/s2a/internal/record/internal/halfconn/counter_test.go, security/s2a/internal/record/internal/halfconn/expander.go, security/s2a/internal/record/internal/halfconn/expander_test.go, security/s2a/internal/record/internal/halfconn/halfconn.go, security/s2a/internal/record/internal/halfconn/halfconn_test.go, security/s2a/internal/record/record.go, security/s2a/internal/record/record_test.go, security/s2a/s2a.go, security/s2a/s2a_options.go, security/s2a/s2a_options_test.go, security/s2a/s2a_test.go
While adding a package description to some files, I noticed that the Apache License wasn't added to many of the files I created. This PR adds the license to all of those files. Also, while adding the license, some of the imports were rearranged because I enabled a different setting in my `goimports` which sorts the imports properly when saving a file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/matthewstevenson88/grpc-go/54)
=> Add Apache License to files

security/s2a/internal/record/record.go, security/s2a/internal/record/record_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/matthewstevenson88/grpc-go/49)
=> Implement record write

security/s2a/internal/fakehandshaker/main.go, security/s2a/internal/fakehandshaker/service/s2a_service.go, security/s2a/internal/fakehandshaker/service/s2a_service_test.go, security/s2a/s2a_e2e_test.go
Added e2e testing using the fake handshaker service. Since `Read` and `Write` are currently unimplemented, I temporarily replaced the implementation with:
```
func (p *conn) Read(b []byte) (n int, err error) {
return p.Conn.Read(b)
}
func (p *conn) Write(b []byte) (n int, err error) {
return p.Conn.Write(b)
}
```
The e2e test starts up 2 fake handshaker services (1 for the client and 1 for the server) and then the server. These are run using separate Go routines.
Finally, the client is started up and blocks until a connection is made with the server, and verifies that it received the correct message from the server.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/matthewstevenson88/grpc-g …
=> Add S2A E2E test using fake handshaker service

security/s2a/examples/e2e_client/main.go
Fixed the S2A E2E greeter client by adding a local identity as well as fixing the response message string comparison.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/matthewstevenson88/grpc-go/60)
=> Fix S2A E2E greeter client

security/s2a/s2a_options.go, security/s2a/s2a_options_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/matthewstevenson88/grpc-go/61)
=> S2a options set default LocalIdentity for ClientOptions

security/s2a/internal/record/record.go, security/s2a/internal/record/record_test.go
Fixed the issue of not clearing the body of the message when receiving a new session ticket. This caused issues when communication with a Go/C++ greeter server. 
Also, I changed the code to clear the entire `p.pendingApplicationData`. Before, we didn't clear the entire buffer in case there were trailing bytes that we were still interested in. However, for handshake messages and alerts, I don't think there will ever be trailing bytes at the end.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/matthewstevenson88/grpc-go/62)
=> Fix clearing new session ticket message

security/s2a/internal/authinfo/authinfo.go, security/s2a/internal/fakehandshaker/main.go, security/s2a/internal/handshaker/handshaker.go, security/s2a/internal/record/internal/aeadcrypter/aeadcrypter.go, security/s2a/internal/record/internal/halfconn/halfconn.go, security/s2a/internal/record/record.go, security/s2a/s2a.go
Added package documentation to certain key files. This should give a very brief overview of what each of these packages are responsible for.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/matthewstevenson88/grpc-go/55)
=> Add package documentation to certain files

security/s2a/internal/record/record.go, security/s2a/internal/record/record_test.go
Added the functionality for sending a key update request back to the peer. What remains now is to add locks to `Read`, `Write`, and `Close`, and also around the part of `Read` where the key update message is sent back to the peer.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/matthewstevenson88/grpc-go/57)
=> Send key updates on request

security/s2a/internal/record/record.go, security/s2a/internal/record/record_test.go
A small PR to define the max number of records that can fit into outRecordsBuf as a constant.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/matthewstevenson88/grpc-go/63)
=> Change outBufMaxRecords into a constant

security/s2a/internal/record/record.go
Added locks to Read, Write, and Close.
These locks are needed to safely read, write, and close concurrently.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/matthewstevenson88/grpc-go/64)
=> Add locks to Read and Write

security/s2a/internal/record/record.go, security/s2a/internal/record/record_test.go
Added resumption handling to the S2A client. While adding support for resumption handling, I also refactored some of the code in the `Read` implementation to break up the function into smaller, easier to understand parts. This was necessary since the handshake message handling was getting very large.
Currently, key updates and session tickets can be coalesced into a single record. I haven't added any tests for this case yet, since we don't know if this should be supported or not.
The current tests verify the following:
1) Consecutive tickets in separate records
2) Multiple tickets in the same record
3) Large tickets fragmented across records
4) Consecutive tickets fragmented across records
5) Tickets that are fragmented in the handshake header (This should also work for fragmented key …
=> Add resumption handling to the S2A client

security/s2a/internal/record/record.go, security/s2a/internal/record/record_test.go
Changed the behavior of the alert handling to return an error and close the connection on every alert type. The closing of the connection is handled by the gRPC stack when an error is thrown.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/matthewstevenson88/grpc-go/68)
=> Change alert handling to close on every alert type

security/s2a/internal/handshaker/handshaker.go, security/s2a/internal/record/record.go, security/s2a/internal/record/record_test.go, security/s2a/internal/record/ticketsender.go, security/s2a/internal/record/ticketsender_test.go
This PR is a followup to #67 .
Added support for sending session tickets to S2A once we reach the limit on the number of session tickets or stop receiving session tickets.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/matthewstevenson88/grpc-go/69)
=> Add support for sending session tickets to S2A
